config/routes.rb
Passkeeper::Application.routes.draw do
  resources :groups

  resources :passwords

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  root :to =>'home#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :users, :notes, :passwords, :user_ids, :group_id
  has_and_belongs_to_many :users
  has_and_belongs_to_many :passwords
  belongs_to :group
  has_many :groups
  validates :users, :length => {:minimum => 1 }

  def update_password_hashes(current_user, user_session)
    passwords.each do |p|
      p.create_hashes(p.password_hashes.find_by_user_id(current_user.id).decrypt(user_session[:private_key]))
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
        unless @group.users.include? current_user 
          format.html { render :file => "public/403.html", :status => :forbidden }
        else
          format.html # show.html.erb
          format.json { render json: @group }
        end
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])

    respond_to do |format|
        unless @group.users.include? current_user 
          format.html { render :file => "public/403.html", :status => :forbidden }
        else
            format.html
            format.json
        end
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save and @group.update_password_hashes current_user, user_session
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      unless @group.users.include? current_user 
          format.html { render :file => "public/403.html", :status => :forbidden }
      else
          if @group.update_attributes(params[:group]) and @group.update_password_hashes current_user, user_session
            format.html { redirect_to @group, notice: 'Group was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @group.errors, status: :unprocessable_entity }
          end
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])

    if @group.users.include? current_user 
        result = @group.destroy
    end

    respond_to do |format|
      unless result
          format.html { render :file => "public/403.html", :status => :forbidden }
      else
        format.html { redirect_to groups_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
  <div class="field">
    <%= f.label :users %><br />
    <%= f.collection_select :user_ids, User.all, :id, :email,{}, {:multiple=>true} %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.collection_select :group_id, current_user.groups.reject { |g| g.id == @group.id }.sort_by {|group| group.name}, :id, :name, { :include_blank => true } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
<% if !group.groups.empty? or group.group.nil? %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>
<%= link_to 'Home', root_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>
<p>
  <b>Notes:</b>
  <pre><%= @group.notes %></pre>
</p>
<p>
  <b>Users:</b>
  <% @group.users.each do |u| %>
  <%= u.email %>
  <% end %>
</p>
<p>
<b>Passwords:</b>
    <ul>
        <% @group.passwords.each do |p| %>
            <li>
            <%= link_to p.user, p %> <%= p.server %>
            </li>
  <% end %>
  </ul>
<%= link_to 'New Password', new_password_path %>
  </p>
<b>Groups:</b>
    <ul>
        <% @group.groups.each do |g| %>
            <li>
            <%= link_to g.name, g %>
            </li>
  <% end %>
  </ul>
  </p>
  <% unless @group.group.nil? %>
<p>
  <b>Parent Group:</b>
  <%= link_to @group.group.name, @group.group %>
</p>
<% end %>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', root_path %>