config/routes.rb
Passkeeper::Application.routes.draw do
  resources :groups

  resources :passwords

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  root :to =>'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_group.html.erb
<h2><%= link_to group.name, group %></h2>
<% if group.passwords.any? %>
<table>
  <tr>
    <th>User</th>
    <th>Server</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% group.passwords.sort_by {|obj| obj.server }.sort_by {|obj| obj.user }.each do |password| %>
  <tr>
    <td><%= password.user %></td>
    <td><%= password.server %></td>
    <td><%= password.notes %></td>
    <td><%= link_to 'Show', password %></td>
  </tr>
<% end %>
</table>
<% end %>
<ul>
<% group.groups.sort_by { |obj| obj.name }.each do |g| %>
  <% if current_user.groups.find_by_id g.id %>
  <li><%= render :partial => "group", :locals => { :group => g } %></li>
  <% end %>
<% end %>
</ul>

app/views/home/index.html.erb
<h1>Hello!</h1>

<% unless user_signed_in? -%>
    <p><%= link_to 'Sign up as User', new_user_registration_path %></p>
    <p><%= link_to 'Sign in as User', new_user_session_path %></p>
<% end -%>

<% if user_signed_in? -%>
    <p>Currently signed in as '<%= current_user.email %>'</p>
    <p>
    <%= link_to 'Edit User', edit_user_registration_path %> |
    <%= link_to 'Sign Out', destroy_user_session_path, :method=>:delete %>
    </p>
    <p><%= link_to 'Groups', groups_path %> |
    <%= link_to 'New Group', new_group_path %></p>
    <p><%= link_to 'Passwords', passwords_path %> |
    <%= link_to 'New Password', new_password_path %></p>
    <ul>
    <% current_user.groups.find_all_by_group_id(nil).sort_by { |obj| obj.name }.each do |g| %>
      <li><%= render :partial => "group", :locals => { :group => g } %></li>
    <% end %>
    </ul>
<% end -%>